// Code generated by internal/ops/cmd/gen from internal/ops/ops.go. DO NOT EDIT.

package ai

// ToolSpecs returns the tool catalog exposed to the LLM. The names match the
// JSONL ops dispatched by internal/runtime.Session.Dispatch — this is
// intentional: the LLM can read CLAUDE.md / agent docs and pick the same op
// names a human operator would.
//
// Schemas are deliberately minimal — overspec'd schemas hurt model recall
// (extra fields the model has to reason about) without buying us safety beyond
// what the agent ops already enforce at runtime. That is why an op's AI schema
// is narrower than its JSONL contract: internal/ops declares both.
func ToolSpecs() []ToolSpec {
	return []ToolSpec{
		{
			Name:        "navigate",
			Description: "Load a URL in the current tab. Use this first if the goal references a site.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"url":  map[string]any{"type": "string", "description": "Absolute URL"},
					"wait": map[string]any{"type": "string", "enum": []string{"load", "stable", "idle", "none"}},
				},
				"required": []string{"url"},
			},
		},
		{
			Name:        "extract",
			Description: "Return a compact accessibility tree of the current page with @refs you can click/type on. Always call this before clicking or typing on an unknown page.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"level":    map[string]any{"type": "string", "description": "Default content. Use skeleton for huge pages.", "enum": []string{"skeleton", "content", "full"}},
					"selector": map[string]any{"type": "string", "description": "Optional CSS selector to scope the extraction"},
				},
			},
		},
		{
			Name:        "click",
			Description: "Click an element by its @ref (from extract). Refs become stale after navigation — re-extract first.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"ref": map[string]any{"type": "string", "description": "@ref of the element, e.g. @5"},
				},
				"required": []string{"ref"},
			},
		},
		{
			Name:        "type",
			Description: "Type text into an input identified by @ref.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"ref":  map[string]any{"type": "string", "description": "@ref of the input"},
					"text": map[string]any{"type": "string", "description": "Text to type"},
				},
				"required": []string{"ref", "text"},
			},
		},
		{
			Name:        "press",
			Description: "Press a keyboard key (e.g. Enter, Escape, ArrowDown). Optional ref to focus first.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"key": map[string]any{"type": "string", "description": "Key name"},
					"ref": map[string]any{"type": "string", "description": "Optional @ref to focus"},
				},
				"required": []string{"key"},
			},
		},
		{
			Name:        "hover",
			Description: "Hover over an element by @ref (reveals dropdowns, tooltips).",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"ref": map[string]any{"type": "string", "description": "@ref"},
				},
				"required": []string{"ref"},
			},
		},
		{
			Name:        "select",
			Description: "Pick option(s) in a <select> by @ref.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"ref":    map[string]any{"type": "string", "description": "@ref of <select>"},
					"values": map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
				},
				"required": []string{"ref", "values"},
			},
		},
		{
			Name:        "scroll_by",
			Description: "Scroll the viewport vertically by dy pixels (positive=down).",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"dy": map[string]any{"type": "integer", "description": "Pixels (signed)"},
				},
				"required": []string{"dy"},
			},
		},
		{
			Name:        "scroll_to",
			Description: "Scroll to absolute Y or to bottom.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"y":      map[string]any{"type": "integer", "description": "Absolute Y"},
					"bottom": map[string]any{"type": "boolean"},
				},
			},
		},
		{
			Name:        "eval",
			Description: "Evaluate a JavaScript expression on the page. Returns the stringified value. Use sparingly — prefer extract+click.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"expr": map[string]any{"type": "string", "description": "JS expression"},
					"ref":  map[string]any{"type": "string", "description": "Optional @ref bound as `this`"},
				},
				"required": []string{"expr"},
			},
		},
		{
			Name:        "wait",
			Description: "Wait for a CSS selector to appear or a fixed delay.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"selector": map[string]any{"type": "string", "description": "CSS selector"},
					"ms":       map[string]any{"type": "integer", "description": "Fixed delay in ms"},
				},
			},
		},
		{
			Name:        "errors",
			Description: "Return console + network errors observed on the current page.",
			InputSchema: map[string]any{
				"type":       "object",
				"properties": map[string]any{},
			},
		},
		{
			Name:        "url",
			Description: "Return the current page URL and title.",
			InputSchema: map[string]any{
				"type":       "object",
				"properties": map[string]any{},
			},
		},
		{
			Name:        "done",
			Description: "Signal that the goal is complete. Provide the answer / outcome.",
			InputSchema: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"answer": map[string]any{"type": "string", "description": "Final answer or short summary of the outcome"},
				},
				"required": []string{"answer"},
			},
		},
	}
}
