// Code generated by internal/ops/cmd/gen from internal/ops/ops.go. DO NOT EDIT.

package runtime

// handlers binds every catalog op carrying the "jsonl" surface to its
// hand-written method on *Session. Dispatch routes through this table and Ops
// enumerates it, so the JSONL surface is exactly the catalog's "jsonl" set by
// construction, with no list left to keep in sync.
//
// The method bodies live in ops.go. Adding an op to the catalog regenerates
// this table, and the build fails until its method exists.
var handlers = map[string]handler{
	"back":       (*Session).opBack,
	"check":      (*Session).opCheck,
	"click":      (*Session).opClick,
	"close":      (*Session).opClose,
	"dblclick":   (*Session).opDblclick,
	"dialog":     (*Session).opDialog,
	"errors":     (*Session).opErrors,
	"eval":       (*Session).opEval,
	"extract":    (*Session).opExtract,
	"fill":       (*Session).opFill,
	"forward":    (*Session).opForward,
	"hover":      (*Session).opHover,
	"init":       (*Session).opInit,
	"navigate":   (*Session).opNavigate,
	"press":      (*Session).opPress,
	"reload":     (*Session).opReload,
	"screenshot": (*Session).opScreenshot,
	"scroll_by":  (*Session).opScrollBy,
	"scroll_to":  (*Session).opScrollTo,
	"select":     (*Session).opSelect,
	"tabs":       (*Session).opTabs,
	"type":       (*Session).opType,
	"uncheck":    (*Session).opUncheck,
	"url":        (*Session).opURL,
	"wait":       (*Session).opWait,
}
