// Code generated by internal/ops/cmd/gen from internal/ops/ops.go. DO NOT EDIT.

package mcp

import mcpgo "github.com/mark3labs/mcp-go/mcp"

// toolDefs pairs every catalog op carrying the "mcp" surface with its
// hand-written handler method. registerTools registers it and Tools enumerates
// it, so the registered set is the catalog's "mcp" set by construction.
//
// Descriptions, enums and defaults come from the catalog's MCP SurfaceSpec:
// they are what an MCP client sees in tools/list, so they are declared once
// there rather than restated here. The handler bodies stay hand-written in
// tools.go.
func toolDefs() []toolDef {
	return []toolDef{
		{mcpgo.NewTool("back",
			mcpgo.WithDescription("Navigate back in browser history. Returns the new URL."),
		), (*Server).handleBack},

		{mcpgo.NewTool("click",
			mcpgo.WithDescription("Click an element by its ref (@1, @2, ...). Ref comes from the last snapshot. Auto-waits for attached + visible + enabled + hit-target, then returns a compact a11y-ref diff (snapshot=diff, default), a skeleton extract (full), or nothing (none)."),
			mcpgo.WithString("ref", mcpgo.Required(), mcpgo.Description("Element ref from the last snapshot (e.g. @3 or 3)")),
			mcpgo.WithString("button", mcpgo.Description("Mouse button: left, right, or middle (default: left)"), mcpgo.Enum("left", "right", "middle"), mcpgo.DefaultString("left")),
			mcpgo.WithString("snapshot", mcpgo.Description("none | diff | full (default: diff)"), mcpgo.Enum("none", "diff", "full"), mcpgo.DefaultString("diff")),
		), (*Server).handleClick},

		{mcpgo.NewTool("dialog",
			mcpgo.WithDescription("Set how JavaScript dialogs (alert/confirm/prompt) are handled. Default is accept. Applies to subsequent dialogs."),
			mcpgo.WithString("action", mcpgo.Description("accept (default) or dismiss"), mcpgo.Enum("accept", "dismiss"), mcpgo.DefaultString("accept")),
			mcpgo.WithString("text", mcpgo.Description("Prompt response text when action=accept")),
		), (*Server).handleDialog},

		{mcpgo.NewTool("drag",
			mcpgo.WithDescription("Drag an element from one ref to another. Simulates a full mouse drag-and-drop sequence."),
			mcpgo.WithString("from", mcpgo.Required(), mcpgo.Description("Source element ref")),
			mcpgo.WithString("to", mcpgo.Required(), mcpgo.Description("Target element ref")),
			mcpgo.WithNumber("steps", mcpgo.Description("Intermediate mouse move steps (default 10)"), mcpgo.DefaultNumber(10)),
		), (*Server).handleDrag},

		{mcpgo.NewTool("emulate",
			mcpgo.WithDescription("Emulate a device: viewport size, devicePixelRatio, mobile flag, touch input, user-agent, prefers-color-scheme, and safe-area insets. Use it before testing a responsive or mobile-only UI — without it the page is a 1920x1080 desktop with pointer:fine, so a phone shell or a coarse-pointer media query never activates. Pass a preset via `device`, or explicit width/height. For a standalone PWA on a notched iPhone also pass safe_area_top=59 and safe_area_bottom=34: without them env(safe-area-inset-*) is 0 and every header or bar that pads the status bar or home indicator is measured wrong. Pass reset=true to go back to a plain desktop tab. Invalidates refs: re-snapshot afterwards."),
			mcpgo.WithString("device", mcpgo.Description("Preset: iphone-se, iphone-14, iphone-14-pro, iphone-14-pro-max, pixel-7, pixel-8-pro, ipad, ipad-pro, desktop, desktop-2k")),
			mcpgo.WithNumber("width", mcpgo.Description("Viewport width in CSS pixels (overrides the preset)")),
			mcpgo.WithNumber("height", mcpgo.Description("Viewport height in CSS pixels (overrides the preset)")),
			mcpgo.WithNumber("device_scale_factor", mcpgo.Description("devicePixelRatio, e.g. 3 for a modern iPhone (default 1, or the preset's)")),
			mcpgo.WithBoolean("mobile", mcpgo.Description("Mobile viewport semantics: meta viewport, mobile scrollbars, screen size")),
			mcpgo.WithBoolean("touch", mcpgo.Description("Touch input emulation: pointer:coarse, navigator.maxTouchPoints > 0, touch events")),
			mcpgo.WithString("user_agent", mcpgo.Description("Override navigator.userAgent and the User-Agent header")),
			mcpgo.WithString("color_scheme", mcpgo.Description("Emulate prefers-color-scheme"), mcpgo.Enum("dark", "light", "no-preference")),
			mcpgo.WithNumber("safe_area_top", mcpgo.Description("env(safe-area-inset-top) in CSS pixels (59 on an iPhone 15 Pro Max in standalone mode)")),
			mcpgo.WithNumber("safe_area_right", mcpgo.Description("env(safe-area-inset-right) in CSS pixels")),
			mcpgo.WithNumber("safe_area_bottom", mcpgo.Description("env(safe-area-inset-bottom) in CSS pixels (34 for the iPhone home indicator)")),
			mcpgo.WithNumber("safe_area_left", mcpgo.Description("env(safe-area-inset-left) in CSS pixels")),
			mcpgo.WithBoolean("reset", mcpgo.Description("Drop every emulation override and restore the real desktop viewport and UA"), mcpgo.DefaultBool(false)),
		), (*Server).handleEmulate},

		{mcpgo.NewTool("eval",
			mcpgo.WithDescription("Evaluate a JavaScript expression in the page and return its serialized value. Async expressions are awaited. Use this as an escape hatch for anything the other tools can't do (read localStorage, dispatch a custom event, scroll, etc.)."),
			mcpgo.WithString("expression", mcpgo.Required(), mcpgo.Description("JS expression. Top-level await OK.")),
			mcpgo.WithString("ref", mcpgo.Description("Optional @ref to scope `this` to an element")),
			mcpgo.WithNumber("timeout_ms", mcpgo.Description("Per-call deadline in milliseconds (default 8000)"), mcpgo.DefaultNumber(8000)),
		), (*Server).handleEval},

		{mcpgo.NewTool("fill_form",
			mcpgo.WithDescription("Fill multiple form fields in one call. Pass a JSON object mapping refs to values: {\"@1\": \"John\", \"@2\": \"john@example.com\"}"),
			mcpgo.WithString("fields", mcpgo.Required(), mcpgo.Description("JSON object mapping @ref to text value")),
		), (*Server).handleFillForm},

		{mcpgo.NewTool("forward",
			mcpgo.WithDescription("Navigate forward in browser history. Returns the new URL."),
		), (*Server).handleForward},

		{mcpgo.NewTool("hover",
			mcpgo.WithDescription("Hover over an element by ref. Returns a compact a11y-ref diff (snapshot=diff, default), a skeleton extract (full), or nothing (none)."),
			mcpgo.WithString("ref", mcpgo.Required(), mcpgo.Description("Element ref from the last snapshot")),
			mcpgo.WithString("snapshot", mcpgo.Description("none | diff | full (default: diff)"), mcpgo.Enum("none", "diff", "full"), mcpgo.DefaultString("diff")),
		), (*Server).handleHover},

		{mcpgo.NewTool("navigate",
			mcpgo.WithDescription("Navigate to a URL without a full snapshot. Returns only status + title + load time. Use when you don't need the DOM yet (e.g. chaining click-through pages)."),
			mcpgo.WithString("url", mcpgo.Required(), mcpgo.Description("Absolute URL to navigate to (https://...)")),
			mcpgo.WithString("wait", mcpgo.Description("domcontentloaded (default), load, stable, idle, none"), mcpgo.Enum("domcontentloaded", "load", "stable", "idle", "none"), mcpgo.DefaultString("domcontentloaded")),
		), (*Server).handleNavigate},

		{mcpgo.NewTool("press",
			mcpgo.WithDescription("Press a keyboard key. If `ref` is provided, focus that element first; otherwise the key fires on the document."),
			mcpgo.WithString("key", mcpgo.Required(), mcpgo.Description("Key name: Enter, Tab, Escape, ArrowDown, ArrowUp, PageDown, Backspace, ...")),
			mcpgo.WithString("ref", mcpgo.Description("Optional element ref to focus before pressing")),
		), (*Server).handlePress},

		{mcpgo.NewTool("screenshot",
			mcpgo.WithDescription("Capture the current page (or one element by ref) as an image embedded in the MCP result. Defaults to WebP quality 60 — typically 30-70% lighter than JPEG/PNG for UI captures. Use annotate=true to overlay numbered borders on interactive elements."),
			mcpgo.WithString("ref", mcpgo.Description("Capture only this element by @ref")),
			mcpgo.WithBoolean("full_page", mcpgo.Description("Capture the full scrollable page instead of the viewport"), mcpgo.DefaultBool(false)),
			mcpgo.WithString("format", mcpgo.Description("Image format: webp (default), jpeg, png"), mcpgo.Enum("webp", "jpeg", "png"), mcpgo.DefaultString("webp")),
			mcpgo.WithNumber("quality", mcpgo.Description("Quality 1-100 for webp/jpeg (default 60). Ignored for png."), mcpgo.DefaultNumber(60)),
			mcpgo.WithBoolean("annotate", mcpgo.Description("Overlay numbered borders on interactive elements (forces PNG output)"), mcpgo.DefaultBool(false)),
		), (*Server).handleScreenshot},

		{mcpgo.NewTool("select",
			mcpgo.WithDescription("Select one or more options in a <select> element by ref. Returns a compact a11y-ref diff (snapshot=diff, default), a skeleton extract (full), or nothing (none)."),
			mcpgo.WithString("ref", mcpgo.Required(), mcpgo.Description("Element ref of the <select>")),
			mcpgo.WithString("value", mcpgo.Required(), mcpgo.Description("Option value or visible label to select. For multi-select, pass JSON array as string (e.g. \"[\\\"a\\\",\\\"b\\\"]\").")),
			mcpgo.WithString("snapshot", mcpgo.Description("none | diff | full (default: diff)"), mcpgo.Enum("none", "diff", "full"), mcpgo.DefaultString("diff")),
		), (*Server).handleSelect},

		{mcpgo.NewTool("snapshot",
			mcpgo.WithDescription("All-in-one page report: status, console+network errors, compact DOM with refs (@1, @2, ...). If `url` is given, navigate first; otherwise snapshot the current page. This is the canonical first call when an agent visits or revisits a page. Refs from this snapshot stay valid until the next snapshot or navigate."),
			mcpgo.WithString("url", mcpgo.Description("Absolute URL to navigate to before snapshotting (optional — omit to snapshot the current page)")),
			mcpgo.WithString("wait", mcpgo.Description("Wait strategy when navigating: domcontentloaded (default), load, stable, idle, none"), mcpgo.Enum("domcontentloaded", "load", "stable", "idle", "none"), mcpgo.DefaultString("domcontentloaded")),
			mcpgo.WithString("level", mcpgo.Description("DOM extraction depth: skeleton (interactive only, smallest), content (default — adds text), full (everything named)"), mcpgo.Enum("skeleton", "content", "full"), mcpgo.DefaultString("content")),
			mcpgo.WithString("selector", mcpgo.Description("Optional CSS selector to scope the DOM extraction to a subtree")),
		), (*Server).handleSnapshot},

		{mcpgo.NewTool("swipe",
			mcpgo.WithDescription("Swipe with a real single-finger touch gesture (touchstart/touchmove/touchend) between two viewport coordinates in CSS pixels. Use this — not drag — to test a mobile drawer, carousel, or pull-to-refresh: drag emits mouse events, which a touch-only handler ignores. Enables touch emulation automatically if it is off."),
			mcpgo.WithNumber("from_x", mcpgo.Required(), mcpgo.Description("Start X in CSS pixels, relative to the viewport")),
			mcpgo.WithNumber("from_y", mcpgo.Required(), mcpgo.Description("Start Y in CSS pixels, relative to the viewport")),
			mcpgo.WithNumber("to_x", mcpgo.Required(), mcpgo.Description("End X in CSS pixels")),
			mcpgo.WithNumber("to_y", mcpgo.Required(), mcpgo.Description("End Y in CSS pixels")),
			mcpgo.WithNumber("duration_ms", mcpgo.Description("Gesture duration in milliseconds (default 300). Shorter = flick, longer = slow drag."), mcpgo.DefaultNumber(300)),
			mcpgo.WithNumber("steps", mcpgo.Description("Intermediate touchmove events (default 12)"), mcpgo.DefaultNumber(12)),
			mcpgo.WithString("snapshot", mcpgo.Description("none | diff | full (default: diff)"), mcpgo.Enum("none", "diff", "full"), mcpgo.DefaultString("diff")),
		), (*Server).handleSwipe},

		{mcpgo.NewTool("tabs",
			mcpgo.WithDescription("List open browser tabs with their URLs, titles, and indices. Use the index with 'switch' action to change the active tab."),
			mcpgo.WithString("action", mcpgo.Description("list (default), switch, close, new"), mcpgo.Enum("list", "switch", "close", "new"), mcpgo.DefaultString("list")),
			mcpgo.WithNumber("index", mcpgo.Description("Tab index for switch/close actions")),
			mcpgo.WithString("url", mcpgo.Description("URL for action=new (blank tab when omitted)")),
		), (*Server).handleTabs},

		{mcpgo.NewTool("type",
			mcpgo.WithDescription("Type text into an input/textarea by ref. Set submit=true to press Enter after typing. Returns a compact a11y-ref diff (snapshot=diff, default), a skeleton extract (full), or nothing (none)."),
			mcpgo.WithString("ref", mcpgo.Required(), mcpgo.Description("Element ref from the last snapshot")),
			mcpgo.WithString("text", mcpgo.Required(), mcpgo.Description("Text to type (the field is cleared first)")),
			mcpgo.WithBoolean("submit", mcpgo.Description("If true, press Enter after typing"), mcpgo.DefaultBool(false)),
			mcpgo.WithString("snapshot", mcpgo.Description("none | diff | full (default: diff)"), mcpgo.Enum("none", "diff", "full"), mcpgo.DefaultString("diff")),
		), (*Server).handleType},

		{mcpgo.NewTool("upload",
			mcpgo.WithDescription("Upload file(s) to a file input element by ref."),
			mcpgo.WithString("ref", mcpgo.Required(), mcpgo.Description("File input element ref")),
			mcpgo.WithString("paths", mcpgo.Required(), mcpgo.Description("File path or JSON array of file paths")),
		), (*Server).handleUpload},

		{mcpgo.NewTool("wait_for",
			mcpgo.WithDescription("Wait for a condition: @ref or CSS selector to become visible, text to appear, or just a timeout. At least one of ref/selector/text/timeout_ms must be given."),
			mcpgo.WithString("ref", mcpgo.Description("Element ref from the last snapshot (e.g. @3)")),
			mcpgo.WithString("selector", mcpgo.Description("CSS selector to wait for")),
			mcpgo.WithString("text", mcpgo.Description("Visible text substring to wait for")),
			mcpgo.WithString("url", mcpgo.Description("Wait until the current URL contains this substring")),
			mcpgo.WithString("load", mcpgo.Description("Page load state: load, domcontentloaded, idle, stable, none"), mcpgo.Enum("load", "domcontentloaded", "idle", "stable", "none")),
			mcpgo.WithString("state", mcpgo.Description("Element state when waiting on ref/selector: attached, visible, hidden, enabled, stable (default: visible)"), mcpgo.Enum("attached", "visible", "hidden", "enabled", "stable"), mcpgo.DefaultString("visible")),
			mcpgo.WithNumber("timeout_ms", mcpgo.Description("Maximum wait time in milliseconds (default 5000, max 30000)"), mcpgo.DefaultNumber(5000)),
		), (*Server).handleWaitFor},
	}
}
